name: Build and Push Caddy Docker Image

on:
  schedule:
    # 每天凌晨检查更新 (UTC时间)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发

env:
  IMAGE_NAME: caddy
  # 使用你的GitHub用户名或组织名替换下面的<YOUR_GITHUB_USERNAME_OR_ORG>
  GITHUB_REGISTRY: ghcr.io/hiccup90

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest Caddy version
        id: caddy-version
        run: |
          LATEST=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name')
          echo "Latest Caddy version: $LATEST"
          echo "version=$LATEST" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.caddy-version.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.version=${{ steps.caddy-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update README with latest version
        run: |
          echo "Latest Caddy version with custom plugins: ${{ steps.caddy-version.outputs.version }}" > README.md
          echo "Image available at: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}" >> README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest version ${{ steps.caddy-version.outputs.version }}" || exit 0
          git push
